### ISSUE TITLE
Privacy concern

### ISSUE THREAD

**Issue by nafizb** [safaorhan/nerdesiniz#1]
I think sharing location on these kind of apps will cause some problems in near future. Neither i see disclaimer document nor linked privacy policy to repo. That increase my suspicion

Also note that author of the repo is safaorhan. When you mixed the letters, it becomes NSA ORHAFA. Nothing to say...

Concerned Citizen

**Comment by safaorhan** [comment]
Is it crazy how saying sentences backwards creates backwards sentences saying how crazy it is?
